name: gofmt

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: gofmt
      run: $([ $(find . -name "*.go" | xargs gofmt -l 2>&1 | wc -c) = "0" ])
