name: testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: docker-compose run --rm --name test registry go test -timeout 30s ./...
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: docker-compose run --rm --name integration-test registry go test -timeout 30s --tags=integration ./...
